package com.ddchen.test1;

import org.junit.Test;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'yuer' at '12/28/16 2:09 PM' with Gradle 3.2.1
 *
 * @author yuer, @date 12/28/16 2:09 PM
 */
public class Test1Test {
    @Test public void testSomeLibraryMethod() {
        Test1 test1 = new Test1();
        test1.test();
    }
}
