/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'yuer' at '12/28/16 2:09 PM' with Gradle 3.2.1
 *
 * @author yuer, @date 12/28/16 2:09 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
